DROP TABLE IF EXISTS shops;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS types;
-- maria
-- DROP TABLE shops  IF EXISTS CASCADE;
-- DROP TABLE products IF EXISTS CASCADE;
-- DROP TABLE types IF EXISTS CASCADE;